# Generated by Django 4.0.5 on 2022-07-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(error_messages={'blank': 'Please enter checklist name', 'null': 'Please enter checklist name'}, max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check list',
                'permissions': [('add_checklist', 'Can add checklist')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('change_user', 'Can change user')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.CharField(error_messages={'null': 'Please enter description'}, max_length=250)),
                ('due', models.DateField(error_messages={'invalid': 'Please enter valid date', 'null': 'Please select due date'})),
                ('status', models.CharField(choices=[('NOT_STARTED', 'N/A'), ('IN_PROGRESS', 'In progress'), ('DONE', 'DONE')], default=('NOT_STARTED', 'N/A'), max_length=100)),
                ('list', models.ForeignKey(error_messages={'null': 'Please select checklist'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', related_query_name='items', to='api.checklist')),
                ('people', models.ManyToManyField(to='api.user')),
            ],
            options={
                'permissions': [('add_checklist_item', 'Can add checklist item')],
                'default_permissions': (),
            },
        ),
    ]
